### ISSUE TITLE
FileDataSource$FileDataSourceException

### ISSUE THREAD

**Issue by HiroyukTamura** [HiroyukTamura/Radiko#26]
```
# Crashlytics - plaintext stacktrace downloaded by Hiroyuki Tamura at Mon, 03 Sep 2018 23:50:23 GMT
# URL: https://fabric.io/hiroyuki-tamura/android/apps/com.cks.hiroyuki2.radiko/issues/5b83e2be6007d59fcdf2c299?time=last-seven-days/sessions/5B8B8760007400010E0E44BB2DA1EC30_DNE_1_v2
# Organization: Hiroyuki Tamura
# Platform: android
# Application: Radiko
# Version: 0.1.11 (11)
# Bundle Identifier: com.cks.hiroyuki2.radiko
# Issue #: 322
# Issue ID: 5b83e2be6007d59fcdf2c299
# Session ID: 5B8B8760007400010E0E44BB2DA1EC30_DNE_1_v2
# Date: 2018-09-02T06:48:00Z
# OS Version: 7.1.2
# Device: Redmi Note 3
# RAM Free: 34.3%
# Disk Free: 51.5%

#0. Crashed: main
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:349)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)

--

Non-fatal Exception: com.google.android.exoplayer2.ExoPlaybackException
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:349)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)

Caused by com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /data/user/0/com.cks.hiroyuki2.radiko/files/radiko/AIR-G'（FM北海道）/AIR-G'ヘッドラインニュース_26090705.aac: open failed: ENOENT (No such file or directory)
       at com.google.android.exoplayer2.upstream.FileDataSource.open(SourceFile:70)
       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(SourceFile:147)
       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(SourceFile:844)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:320)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

Caused by java.io.FileNotFoundException: /data/user/0/com.cks.hiroyuki2.radiko/files/radiko/AIR-G'（FM北海道）/AIR-G'ヘッドラインニュース_26090705.aac: open failed: ENOENT (No such file or directory)
       at libcore.io.IoBridge.open(IoBridge.java:455)
       at java.io.RandomAccessFile.(RandomAccessFile.java:247)
       at java.io.RandomAccessFile.(RandomAccessFile.java:128)
       at com.google.android.exoplayer2.upstream.FileDataSource.open(SourceFile:62)
       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(SourceFile:147)
       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(SourceFile:844)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:320)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

Caused by android.system.ErrnoException: open failed: ENOENT (No such file or directory)
       at libcore.io.Posix.open(Posix.java)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
       at libcore.io.IoBridge.open(IoBridge.java:441)
       at java.io.RandomAccessFile.(RandomAccessFile.java:247)
       at java.io.RandomAccessFile.(RandomAccessFile.java:128)
       at com.google.android.exoplayer2.upstream.FileDataSource.open(SourceFile:62)
       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(SourceFile:147)
       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(SourceFile:844)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:320)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

#0. Crashed: main
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:349)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)


```

Posix.java
libcore.io.Posix.open

DLしたAACファイルが見つからない

**Comment by HiroyukTamura** [comment]
duplicate to #26
